
name = "ASU WS 2.0"
license = "MIT"
licenselink = ""
description = "ASU's theme ported for use in Hugo"
homepage = "https://asu.edu/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Suhail Ghafoor"
  homepage = "https://www.public.asu.edu/~saghafoo/"
